### ISSUE TITLE
请问下，如何让自动指定位置破碎

### ISSUE THREAD

**Issue by chongbo2013** [zhanyongsheng/BrokenView#1]
public void animationBroken(View mView){
        BrokenConfig mBrokenConfig=new BrokenConfig();
        mBrokenConfig.complexity=8;
        Point mPaint=new Point(parentLayout.getWidth()/2,parentLayout.getHeight()/2);
        BrokenAnimator mBrokenAnimator=mBrokenView.createAnimator(parentLayout,mPaint,mBrokenConfig);
        mBrokenAnimator.start();

```
}
```

有时候破碎不成功

**Comment by zhanyongsheng** [comment]
这样做是可以的啊，不过要注意传入createAnimator的Point是相对于整个屏幕的坐标，并且传入createAnimator的view也要确保被测量过。我在onWindowFocusChanged里调用以上方法暂未发现问题，不知有时候破碎不成功具体是什么现象？

**Comment by chongbo2013** [comment]
if (fraction > 0.5 && bPressed) {  我修改这个方法， 好像你是根据 View的 百分百来确定他是否可以被 破碎。 我修改这个值，更容易破碎

**Comment by zhanyongsheng** [comment]
fraction是动画进行的百分比，这个的意思是按住View后如果裂痕动画进行到大于80%则不论是否松开手都继续进行下去，不会再有松开时裂痕消失（reverse）效果，不过你说指定位置自动破碎，这就和手指触控没有关系了，这个if也就没什么用啦，bPressed永远是true

**Comment by chongbo2013** [comment]
我现在想，搞个按钮，点击后，他自动 破碎，有点问题。 我可以把我改过的代码发你看看吗哥们

**Comment by zhanyongsheng** [comment]
可以，直接加q也行763261807
